//This c++ code is generated by PictoBlox

//MACROS are defined here
float getDistance(int trig,int echo){
		pinMode(trig,OUTPUT);
		digitalWrite(trig,LOW);
		delayMicroseconds(2);
		digitalWrite(trig,HIGH);
		delayMicroseconds(10);
		digitalWrite(trig,LOW);
		pinMode(echo, INPUT);
		return pulseIn(echo, HIGH)/58.0;
}

//Gloabl Variables are declared here
float my_variable;

void setup() {
	//put your setup code here, to run once:
	Serial.begin(9600);
	
	
}

void loop() {
	//put your main code here, to run repeatedly:
	
	
	my_variable = getDistance(2, 3);
	Serial.println(my_variable);
	delay(0.2 * 1000);
}
